### PR TITLE
Precommit with ruff+codespell

### PR DESCRIPTION
**Pull request by agramfort**
setting up precommit hooks with ruff + codespell

codespell found a few typos :)

feedback welcome

### CODE REVIEW

**Comment by rflamary** [comment]
@agramfort thanks for the PR, tests are not running anymore since last commit. 
https://github.com/scikit-adaptation/skada/actions/runs/8133112804

Could we have a quick test checking that style is valid (flake8 was not needed anymore but can we test it with ruff maybe?).  To detect new contributors that did not install the pre-commit.

**Comment by agramfort** [comment]
@rflamary @kachayev @tgnassou this one is good to go from my end

**Comment by kachayev** [comment]
@agramfort This is cool, very needed tools! I have a question regarding testing/linting flow: testing job is setup to run pre-commit hooks, which contains ruff linter with `--fix` flag. What happens if someone commits unlinted file? I guess it will just fix the code locally in the test container without reporting/failing? 🤔

**Comment by agramfort** [comment]
@kachayev good question. I copied the practice of another repo that has been using this successfully for a few months. Let's see how it goes here. We can always adjust.

**Comment by rflamary** [comment]
well now we know it does not fail since my PR definitely does not respect ruff:
https://github.com/scikit-adaptation/skada/pull/135

**Comment by kachayev** [comment]
That's interesting. In my PRs it actually fails because of files being changed (which is desirable) 🤔 

```
ruff lint skada..........................................................Failed
- hook id: ruff
- files were modified by this hook
- ```

**Comment by rflamary** [comment]
this is very weird no?

**Pull request merged**
