### PR TITLE
[MRG] Separate Lint and Tests + codecov configuration

### PR DESCRIPTION
**Pull request by rflamary**

### CODE REVIEW

**Comment by agramfort** [comment]
what if you run 

pre-commit run -a

locally?

**Comment by rflamary** [comment]
all passed. what is happening with my pre-commit (and the one on teh action...)

**Comment by agramfort** [comment]
do you have precommit that runs locally when you git commit?

**Comment by kachayev** [comment]
@rflamary Your code has changes made in the `__init__.py` file, which is excluded in `ruff.toml` (the very first `exclude`)

**Comment by kachayev** [comment]
I also opened an issue #136 so we don't forget to make `ruff` work for base modules.

**Comment by kachayev** [comment]
I moved the linting error to a non-excluded file, now it works as expected (linting job fails).

**Comment by rflamary** [comment]
thanks so much @kachayev I did not understand what was happening. I will cleanup this and merge the PR (and make the Lint test necessary for merge)

**Pull request merged**
