### PR TITLE
Add frank-wolfe algorithm

### PR DESCRIPTION
**Pull request by antoinedemathelin**
Hi everyone,
I propose to add the Frank-wolfe algorithm to speed KMM. (almost 20 times faster in the small example).
It can be used for KLIEP and Tars too, in the future.

Cf paper https://webdocs.cs.ualberta.ca/~dale/papers/ijcai15.pdf

Cf PR #93 PR #108

### CODE REVIEW

**Comment by rflamary** [comment]
Hello @antoinedemathelin this is great.

I was thinking that we would  add a parameter to qpsolve and insteda have _qpsolve_scipy  and _qpsolve_frank_wolfe functions ? this would be nice because it means that in the methdos one can just apss the solver parameter.

**Comment by rflamary** [comment]
I see that your solver is less general but one can use the general function and taise an error if the constrainst cannot be solve by FW

**Comment by antoinedemathelin** [comment]
Hi @rflamary,
Ok I can do that!

**Comment by rflamary** [comment]
I'm closing this PR since we have the new and improved #167

**Pull request closed without merging**
